version: "3"
services:
  gateway:
    build:
      context: ./.docker/gateway
      dockerfile: Dockerfile
    ports:
      - "7070:80"
    cap_add:
      - ALL
    environment:
      - NGINX_PORT=80
    volumes:
      - ./.docker/gateway/nginx.conf:/etc/nginx/nginx.conf

  influxdb:
    image: influxdb:2.2-alpine
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=loglog-org
      - DOCKER_INFLUXDB_INIT_BUCKET=loglog
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_USER_TOKEN}
    volumes:
      - influxdata:/var/lib/influxdb2
volumes:
  influxdata: { }
